<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>13755c4b-5587-492e-b079-5b1f16720908</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\FuelImport.Aws\FuelImport.Aws.csproj" />
    <ProjectReference Include="..\FuelImport.Core\FuelImport.Core.csproj" />
    <ProjectReference Include="..\FuelImport.Data\FuelImport.Data.csproj" />
    <ProjectReference Include="..\FuelImport.HuggingFace\FuelImport.HuggingFace.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="10.0.11">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="10.0.11" />
  </ItemGroup>

</Project>
