// <auto-generated />
using System;
using FuelImport.Data.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FuelImport.Data.Persistence.Migrations
{
    [DbContext(typeof(FuelImportDbContext))]
    partial class FuelImportDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.11");

            modelBuilder.Entity("FuelImport.Core.Models.FuelEvent", b =>
                {
                    b.Property<int>("FuelEventId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("DashSourceImageId")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("EstimatedMpg")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventTimeLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("EventTimeUtc")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("Gallons")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsEstimated")
                        .HasColumnType("INTEGER");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<string>("LocationName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<decimal?>("MilesSincePrevious")
                        .HasColumnType("TEXT");

                    b.Property<bool>("NeedsReview")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<int?>("Odometer")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("OverallConfidence")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("PricePerGallon")
                        .HasColumnType("TEXT");

                    b.Property<int?>("PumpSourceImageId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewReason")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<decimal?>("TotalPrice")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FuelEventId");

                    b.HasIndex("PumpSourceImageId", "DashSourceImageId")
                        .IsUnique();

                    b.ToTable("FuelEvents");
                });

            modelBuilder.Entity("FuelImport.Core.Models.FuelEventSourceImage", b =>
                {
                    b.Property<int>("FuelEventSourceImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("FuelEventId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SourceImageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("FuelEventSourceImageId");

                    b.HasIndex("FuelEventId", "SourceImageId")
                        .IsUnique();

                    b.ToTable("FuelEventSourceImages");
                });

            modelBuilder.Entity("FuelImport.Core.Models.HumanReview", b =>
                {
                    b.Property<int>("HumanReviewId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CorrectedValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("FuelEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Notes")
                        .HasColumnType("TEXT");

                    b.Property<string>("OriginalValuesJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("ReviewStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ReviewSystem")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ReviewerAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ReviewerName")
                        .HasColumnType("TEXT");

                    b.HasKey("HumanReviewId");

                    b.ToTable("HumanReviews");
                });

            modelBuilder.Entity("FuelImport.Core.Models.ImportBatch", b =>
                {
                    b.Property<int>("ImportBatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CompletedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsDryRun")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RootFolder")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("StartedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ImportBatchId");

                    b.ToTable("ImportBatches");
                });

            modelBuilder.Entity("FuelImport.Core.Models.OcrResult", b =>
                {
                    b.Property<int>("OcrResultId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ConfidenceScore")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedFieldsJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ParsedText")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Provider")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderOperation")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawResponseJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("SourceImageId")
                        .HasColumnType("INTEGER");

                    b.HasKey("OcrResultId");

                    b.ToTable("OcrResults");
                });

            modelBuilder.Entity("FuelImport.Core.Models.SourceImage", b =>
                {
                    b.Property<int>("SourceImageId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CapturedAtLocal")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CapturedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("FileHash")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("FilePath")
                        .IsRequired()
                        .HasMaxLength(1024)
                        .HasColumnType("TEXT");

                    b.Property<int>("Height")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ImageTypeCandidate")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("ImageTypeConfidence")
                        .HasColumnType("TEXT");

                    b.Property<double?>("Latitude")
                        .HasColumnType("REAL");

                    b.Property<double?>("Longitude")
                        .HasColumnType("REAL");

                    b.Property<string>("ManualGroupKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<int>("ProcessingStatus")
                        .HasColumnType("INTEGER");

                    b.Property<string>("RawClassificationJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("RawMetadataJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Width")
                        .HasColumnType("INTEGER");

                    b.HasKey("SourceImageId");

                    b.HasIndex("FileHash")
                        .IsUnique();

                    b.ToTable("SourceImages");
                });

            modelBuilder.Entity("FuelImport.Core.Models.ValidationIssue", b =>
                {
                    b.Property<int>("ValidationIssueId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<int>("FuelEventId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("IssueType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("ResolvedAtUtc")
                        .HasColumnType("TEXT");

                    b.Property<string>("Severity")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SuggestedValue")
                        .HasColumnType("TEXT");

                    b.HasKey("ValidationIssueId");

                    b.ToTable("ValidationIssues");
                });

            modelBuilder.Entity("FuelImport.Core.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Active")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DashboardLabel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedTankGallonsMax")
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ExpectedTankGallonsMin")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxGallonsPerFillUp")
                        .HasColumnType("TEXT");

                    b.Property<decimal?>("MaxMpg")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("NoOdometer")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OdometerMaxKnown")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("OdometerMinKnown")
                        .HasColumnType("INTEGER");

                    b.HasKey("VehicleId");

                    b.ToTable("Vehicles");
                });
#pragma warning restore 612, 618
        }
    }
}
